- django-nonrel/ocl/concepts/models.py
- django-nonrel/ocl/oclapi/management/commands/__init__.py
- django-nonrel/ocl/oclapi/management/commands/import_concepts_to_source.py
Merging in new import behavior
> Import script update

- .gitignore
- README.md
- django-nonrel/ocl/Dockerfile
- django-nonrel/ocl/docker-compose.yml
- django-nonrel/ocl/settings.py
- django-nonrel/ocl/startup.sh
> Docker setup

- django-nonrel/ocl/collection/tests.py
- django-nonrel/ocl/concepts/models.py
- django-nonrel/ocl/concepts/serializers.py
- django-nonrel/ocl/concepts/tests.py
- django-nonrel/ocl/integration_tests/tests.py
- django-nonrel/ocl/mappings/tests.py
- django-nonrel/ocl/requirements.txt
- django-nonrel/ocl/sources/tests.py
> #238 @nopair add basic validation on concept names, modify tests

- django-nonrel/ocl/oclapi/settings/local.py
> #0 add Dev configuration for running tests locally

- django-nonrel/ocl/concepts/custom_validators.py
- django-nonrel/ocl/concepts/models.py
- django-nonrel/ocl/concepts/tests.py
- django-nonrel/ocl/oclapi/settings/__init__.py
- django-nonrel/ocl/oclapi/settings/local.py
- django-nonrel/ocl/sources/models.py
- django-nonrel/ocl/test_helper/base.py
> #241 @selimober adds OpenMRS custom validation to concept creation

- django-nonrel/ocl/concepts/custom_validators.py
- django-nonrel/ocl/concepts/tests.py
> #246 @selimober adds minimum one description requirement

- django-nonrel/ocl/mappings/custom_validators.py
- django-nonrel/ocl/mappings/mixins.py
- django-nonrel/ocl/mappings/models.py
- django-nonrel/ocl/mappings/tests.py
- django-nonrel/ocl/test_helper/base.py
Make sure to Merge with squash!
> #301 @emrah-b add OpenMRS validation to Mapping entity

- django-nonrel/ocl/docker-common.yml
- django-nonrel/ocl/docker-compose.dev.yml
- django-nonrel/ocl/docker-compose.yml
Please note that docker-compose version is changed to 2.1.
> #415 adds volume to Solr container

- django-nonrel/ocl/concepts/tests.py
- django-nonrel/ocl/integration_tests/tests/openmrs_concept_validation.py
Create integration test for concept id with underscore
> Concept id integration tests

- django-nonrel/ocl/integration_tests/tests/all.py
- django-nonrel/ocl/sources/models.py
Reverts OpenConceptLab/oclapi#531
> Revert "Version ext id integration test"

- docker-compose.yml
- ocl/collection/models.py
- ocl/concepts/importer.py
- ocl/concepts/mixins.py
- ocl/concepts/models.py
- ocl/concepts/search_indexes.py
- ocl/concepts/tests.py
- ocl/concepts/views.py
- ocl/integration_tests/tests/all.py
- ocl/integration_tests/tests/bulk_import_validation.py
- ocl/integration_tests/tests/openmrs_concept_validation.py
- ocl/mappings/importer.py
- ocl/mappings/models.py
- ocl/mappings/search_indexes.py
- ocl/mappings/tests.py
- ocl/oclapi/management/commands/import_lookup_values.py
- ocl/oclapi/models.py
- ocl/oclapi/views.py
- ocl/sources/models.py
- ocl/sources/tests.py
- ocl/tasks.py
- ocl/test_helper/base.py
It's not yet ready for merging. Testing in progress...
> DATIM-Metadata-Project#102 Remodel relationship between source version, concept and mappings

- ocl/collection/views.py
- ocl/sources/views.py
Fix bug in processing views where get_object can return multiple objects
> DATIM-Metadata-Project#119 - Fix bug in processing views 

- ocl/collection/filters.py
- ocl/collection/views.py
I tried to revert filters.py to the original, since ultimately no changes were made to the file, but it's still showing up here.
>  DATIM-Metadata-Project Issue 69: add membership filter to collection views

- ocl/nametypes_fixed.json
Fix https://github.com/OpenConceptLab/ocl_issues/issues/129
> Add 'Index Term' name type to nametypes_fixed.json

- ocl/concepts/search_indexes.py
- ocl/concepts/views.py
Address https://github.com/OpenConceptLab/ocl_issues/issues/77
> OpenConceptLab/ocl_issues#77: Add ability to sort concept results by concept ID

- ocl/collection/search_indexes.py
- ocl/collection/views.py
- ocl/sources/search_indexes.py
- ocl/sources/views.py
- solr/config/collection1/conf/schema.xml
Implements https://github.com/OpenConceptLab/ocl_issues/issues/143.
> OpenConceptLab/ocl_issues#143: Allow filtering sources and collections by customValidationSchema

- integration-tests/src/collection.spec.ts
- integration-tests/src/source.spec.ts
- integration-tests/src/testHelper.ts
- ocl/oclapi/filters.py
Address https://github.com/OpenConceptLab/ocl_issues/issues/169.
> ocl_issues#169: Users cannot view their private sources and collections

- integration-tests/src/collection.spec.ts
- integration-tests/src/source.spec.ts
- integration-tests/src/testHelper.ts
- ocl/collection/views.py
- ocl/sources/views.py
- ocl/user_urls.py
- ocl/users/urls.py
Implement https://github.com/OpenConceptLab/ocl_issues/issues/144.
> OpenConceptLab/ocl_issues#144: Implement ability to fetch all collections/ sources owned by a user's orgs

- ocl/sources/models.py
Address https://github.com/OpenConceptLab/ocl_issues/issues/177.
> ocl_issues#177: Source response returning incorrect versions, concepts, mappings urls

- integration-tests/src/mappings.spec.ts
- integration-tests/src/testHelper.ts
- ocl/mappings/views.py
Address https://github.com/OpenConceptLab/ocl_issues/issues/184.
> ocl_issues#184:  404 when retrieving/ updating mappings in Private Collections

- ocl/collection/models.py
Address https://github.com/OpenConceptLab/ocl_issues/issues/191.
> ocl_issues#191: Move unnecessarilly nested reference deletion outside loop

- ocl/collection/views.py
Implement https://github.com/OpenConceptLab/ocl_issues/issues/188.
> ocl_issues#188: Delete all references from a collection

- ocl/collection/views.py
- ocl/tasks.py
Address https://github.com/OpenConceptLab/ocl_issues/issues/193.
> ocl_issues#193: Adding references to a collection from a source/ collection should be asynchronous

- ocl/requirements.txt
Adds support for deletes directly within a bulk import and lots of new OclResourceList features
> Updated requirements to ocldev v0.1.69

- ocl/concepts/models.py
- ocl/concepts/tests.py
Solving https://github.com/OpenConceptLab/ocl_issues/issues/264
> OclIssue-264 | concept display_name/locale updated rules

- ocl/oclapi/search_indexes.py
- ocl/oclapi/settings/common.py
- ocl/requirements.txt
This reverts commit c24f46cb612bc4999acb889b2a3fb9c62569e5d9.
> "OpenConceptLab/ocl_issues#297 revert celery_haystack changes"
